# Site settings
title: Kira Cheung
email: killercentury@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Software Engineer loves rock and code! Interest in functional reactive programming, distributed systems, continous delivery and startup.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kiracheung.com" # the base hostname & protocol for your site
twitter_username: killercentury
github_username:  killercentury

# Build settings
markdown: kramdown
